stylig
knehrybecki/WebsiteSass pull request #3
Opened 2022-02-02 22:24 UTC by knehrybecki

check :)

2022-02-03 08:47 UTC, jpudysz requested changes

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +
remove enter

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +
remove enter

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +                <img src="image/logo.jpg" alt="" class="logo" />
I guess it should be a styled div, not image. This is simple gray box

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +            <img src="image/banner.jpg" alt="" class="banner__img" />
same here, use` border-radius` and `background-color`

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +
remove enter

2022-02-03 08:47 UTC, jpudysz commented on index.html
> +</html>
this sign means that you need to add one enter at the end of the file

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +
remove one enter

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +const menulist= document.querySelector(".menu__list");
add spaces between `=` eg. `const menuList = document...`

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +const buttonhidden= document.querySelector(".fas.fa-times")
use camelCase eg. `buttonShow`

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +const buttonshow= document.querySelector(".fas.fa-bars");
use singlequote: `'.das.fa-bars'`

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +    menulist.style.display= "block";
don't use `;`

2022-02-03 08:47 UTC, jpudysz commented on script.js
> +///i wrote this code for the first time, please on understand :)
enter to remove this sign

2022-02-03 08:47 UTC, jpudysz commented on style/_base.sass
> +    line-height: 1.5em
aa

2022-02-03 08:47 UTC, jpudysz commented on style/_mixin.sass
> +    flex-flow: $flex-flow
aa

2022-02-03 08:47 UTC, jpudysz commented on style/_resetcss.sass
> +    appearance: none
aa

2022-02-03 08:47 UTC, jpudysz commented on style/_resetcss.sass
> +    border: none
you can use reset.css

2022-02-03 08:47 UTC, jpudysz commented on style/_virables.sass
> +
remove unnecessary enters

2022-02-03 08:47 UTC, jpudysz commented on style/_virables.sass
> +$large-desktop: "(min-width: 1280px)"
enter

2022-02-03 08:47 UTC, jpudysz commented on style/header/_action.sass
> +        gap: 15px
aa

2022-02-03 08:47 UTC, jpudysz commented on style/header/_header.sass
> +            @include displayflex(row wrap,center,space-around)
aa

2022-02-03 08:47 UTC, jpudysz commented on style/header/_logo.sass
> +        margin-left: 20px
aa

2022-02-03 08:47 UTC, jpudysz commented on style/header/_menu.sass
> +                padding-left: 20px
aa

2022-02-03 08:47 UTC, jpudysz commented on style/header/_search.sass
> +        margin-left: 0px
aa

2022-02-03 08:47 UTC, jpudysz commented on style/main/_banner.sass
> +    height: 90vh
aa

2022-02-03 08:47 UTC, jpudysz commented on style/style.sass
> +@import "main/banner"
aa

2022-02-04 08:28 UTC, jpudysz approved these changes

2022-02-04 14:51 UTC, knehrybecki commented
ok

2022-02-04 15:02 UTC, merged